# Generated by Django 6.0.7 on 2026-09-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_transaction_source_giftcard'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productitem',
            name='product_item_xor_link',
        ),
        migrations.AddConstraint(
            model_name='productitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('receipt_item__isnull', True), ('transaction__isnull', False)), models.Q(('receipt_item__isnull', False), ('transaction__isnull', True)), _connector='OR'), name='product_item_xor_link'),
        ),
    ]
